services:
  hoarder:
    build: .
    image: hoarder
    environment:
      RESTIC_REPOSITORY: ${RESTIC_REPOSITORY:-?}
      AWS_ACCESS_KEY_ID: ${RESTIC_S3_ACCESS_KEY_ID:-}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY:-}
      RESTIC_PASSWORD_FILE: /run/secrets/restic_repo_password
    # secrets:
    #   - restic_repo_password
    volumes:
      - /run/docker.sock:/run/docker.sock

# secrets:
  # restic_repo_password:
  #   file: ./.restic_repo_password
